### ISSUE TITLE
GitHub Extra Pins

### ISSUE THREAD

**Issue by dmZhan** [ATQQ/atqq#1]
In repo [github-readme-stats](https://github.com/anuraghazra/github-readme-stats),  pins demo is

`[![Readme Card](https://github-readme-stats.vercel.app/api/pin/?username=anuraghazra&repo=github-readme-stats)](https://github.com/anuraghazra/github-readme-stats)`

and yours is

`https://github-readme-stats.anuraghazra1.vercel.app/api/pin/?username=atqq&repo=uni-vue3-ts-template`

Maybe you can stick with him.

Change **github-readme-stats.anuraghazra1.vercel.app** to **github-readme-stats.vercel.app**.

**Comment by ATQQ** [comment]
Solve! 👍🏻
